"""empty message

Revision ID: 3c053eec61c1
Revises: 
Create Date: 2018-02-05 11:30:37.404794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c053eec61c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('articles', sa.Column('post_date', sa.DateTime(), nullable=False))
    op.alter_column('articles', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('articles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('name', mysql.VARCHAR(length=110), nullable=True))
    op.alter_column('articles', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('articles', 'post_date')
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
